name: Upload app image to docker hub 

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push image to Docker Hub
      id: build-image
      env:
        DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and push it to Docker Hub so that it can be deployed to ECS.
        docker build -t $DOCKERHUB_REPOSITORY:$IMAGE_TAG .
        docker push $DOCKERHUB_REPOSITORY:$IMAGE_TAG
        echo "image=$DOCKERHUB_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
